fix versioning

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -129,32 +129,55 @@ jobs:
       - run:
           name: check
           command: |
-            mkdir -p $HOME/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
-            LAST_COMMIT=`git log -1 --pretty=%B`
-            VERSION=`git describe --abbrev=0 --tags`
+            mkdir -p "$HOME/.ssh/" && echo -e 'Host github.com\n\tStrictHostKeyChecking no\n' > ~/.ssh/config
+            LAST_COMMIT="$(git log -1 --pretty=%B)"
+            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
+              # If PR, use PR title instead of last commit msg
+              PR_NUM="${CIRCLE_PULL_REQUEST##*/}"
+              LAST_COMMIT="$(curl -s "${GITHUB_API}repos/${REPO_NAME}/${IMAGE_NAME}/pulls/${PR_NUM}" | jq -r .title)"
+            fi
+            printf 'LAST_COMMIT: %s\n' "${LAST_COMMIT}"
             touch ./.tag
-            if [ ! -z "`git diff $VERSION`" -o -z "$VERSION" ]; then
-              VERSION=${VERSION:-'0.0.0'}
-              MAJOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
+            VERSION="$(git describe --abbrev=0 --tags)"
+            # Diff to prevent pipeline re-runs.
+            if [ -n "$(git diff "$VERSION")" ]; then
+              VERSION=${VERSION:-'v0.0.0'}
+              MAJOR="${VERSION%%.*}"; MAJOR="${MAJOR#v}"; VERSION="${VERSION#*.}"
               MINOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
               PATCH="${VERSION%%.*}"; VERSION="${VERSION#*.}"
-              if echo $LAST_COMMIT | grep "\[\(major\|MAJOR\)\]" > /dev/null; then
-                MAJOR=$((MAJOR+1))
-                echo "$MAJOR.0.0" > ./.tag
-              elif echo $LAST_COMMIT | grep "\[\(minor\|MINOR\)\]" > /dev/null; then
-                MINOR=$((MINOR+1))
-                echo "$MAJOR.$MINOR.0" > ./.tag
-              elif echo $LAST_COMMIT | grep "\[\(patch\|PATCH\)\]" > /dev/null; then
+
+              case "$LAST_COMMIT" in
+              '[patch]'* | '[PATCH]'*)
                 PATCH=$((PATCH+1))
-                echo "$MAJOR.$MINOR.$PATCH" > ./.tag
-              fi
+                echo "v$MAJOR.$MINOR.$PATCH" > ./.tag
+                ;;
+              '[minor]'* | '[MINOR]'*)
+                MINOR=$((MINOR+1))
+                echo "v$MAJOR.$MINOR.0" > ./.tag
+                ;;
+              '[major]'* | '[MAJOR]'*)
+                MAJOR=$((MAJOR+1))
+                echo "v$MAJOR.0.0" > ./.tag
+                ;;
+              # Don't release (nightly images only)
+              '[skip]'* | '[SKIP]'*)
+                echo "Skip release..."
+                ;;
+              # Don't want to run CI.
+              '[skip ci]'* | '[ci skip]'*)
+                echo "Will skip CI..."
+                ;;
+              *)
+                echo "Required prefixes: [major]/[minor]/[patch]/[skip]/[skip ci]"
+                exit 1
+                ;;
+              esac
             else
-              if echo $LAST_COMMIT | grep "\[\(major\|MAJOR\)\]" > /dev/null; then
-                echo "1.0.0" > ./.tag
-              elif echo $LAST_COMMIT | grep "\[\(minor\|MINOR\)\]" > /dev/null; then
-                echo "0.1.0" > ./.tag
-              elif echo $LAST_COMMIT | grep "\[\(patch\|PATCH\)\]" > /dev/null; then
-                echo "0.0.1" > ./.tag
+              if [ -n "$VERSION" ]; then
+                echo "No diff, skip tagging..."
+              else
+                echo "No diff, No tag. Tag it as \"v0.0.0\"."
+                echo "v0.0.0" > ./.tag
               fi
             fi
       - run:
@@ -238,7 +261,7 @@ workflows:
             branches:
               ignore: /.*/
             tags:
-              only: /[0-9]+\.[0-9]+\.[0-9]+/
+              only: /v[0-9]+\.[0-9]+\.[0-9]+/
       - publish:
           requires:
             - build
@@ -246,4 +269,4 @@ workflows:
             branches:
               ignore: /.*/
             tags:
-              only: /[0-9]+\.[0-9]+\.[0-9]+/
+              only: /v[0-9]+\.[0-9]+\.[0-9]+/
